import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs Testing",
  description: "Generated by create next app",
  keyword: "Nhattung",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link className="link" href="/">
            HOME
          </Link>
          <Link className="link" href="/posts">
            POST
          </Link>
          <Link className="link" href="/about">
            ABOUT
          </Link>
          <Link className="link" href="/contact">
            CONTACT
          </Link>
        </header>
        {children}
        <footer>This is Footer</footer>
      </body>
    </html>
  );
}
